M48
; DRILL file {KiCad 9.0.0} date 2025-03-11T15:52:01-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-11T15:52:01-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X187.021Y-48.012
X187.021Y-136.912
T2
X76.591Y-49.886
M30
